export const FETCH_PASSENGER = "FETCH_PASSENGER ";
export const ADD_PASSENGER = "ADD_PASSENGER ";
export const ALL_FLIGHTS = "ALL_FLIGHTS ";
export const FLIGHT_DETAILS = "FLIGHT_DETAILS ";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER ";
export const DELETE_PASSENGER = "DELETE_PASSENGER ";
